import { z } from 'zod'
import { VALIDATION, VALIDATION_MESSAGES } from '@/shared/lib/constants'

export const LoginFormSchema = z.object({
  email: z
    .email(VALIDATION_MESSAGES.EMAIL_INVALID)
    .min(VALIDATION.EMAIL.MIN_LENGTH, VALIDATION_MESSAGES.EMAIL_REQUIRED)
    .max(VALIDATION.EMAIL.MAX_LENGTH, VALIDATION_MESSAGES.EMAIL_TOO_LONG),
  password: z
    .string()
    .min(VALIDATION.PASSWORD.MIN_LENGTH, VALIDATION_MESSAGES.PASSWORD_TOO_SHORT)
    .max(VALIDATION.PASSWORD.MAX_LENGTH, VALIDATION_MESSAGES.PASSWORD_TOO_LONG),
})

export const RegisterFormSchema = z.object({
  email: z
    .email(VALIDATION_MESSAGES.EMAIL_INVALID)
    .min(VALIDATION.EMAIL.MIN_LENGTH, VALIDATION_MESSAGES.EMAIL_REQUIRED)
    .max(VALIDATION.EMAIL.MAX_LENGTH, VALIDATION_MESSAGES.EMAIL_TOO_LONG),
  password: z
    .string()
    .min(VALIDATION.PASSWORD.MIN_LENGTH, VALIDATION_MESSAGES.PASSWORD_TOO_SHORT)
    .max(VALIDATION.PASSWORD.MAX_LENGTH, VALIDATION_MESSAGES.PASSWORD_TOO_LONG),
  name: z
    .string()
    .min(VALIDATION.NAME.MIN_LENGTH, VALIDATION_MESSAGES.NAME_TOO_SHORT)
    .max(VALIDATION.NAME.MAX_LENGTH, VALIDATION_MESSAGES.NAME_TOO_LONG),
})
